### ISSUE TITLE
Query function evaluation security limiting

### ISSUE THREAD

**Issue by marioaquino** [threatgrid/asami#108]
The query capability supports execution of any `clojure.core` functions (via string reference in the query expression), allowing the use of functions which could evaluate arbitrary instructions within the JVM.  This is powerful for constructing queries and it also exposes potential security risks by allowing for instructions that could used for malicious purposes (loading arbitrary file contents, reading the values of arbitrary in-memory data structures, etc).

**Comment by quoll** [comment]
Added a new `sandbox` namespace where we delineate the safe and unsafe functions. Working, but needs thorough testing
