### ISSUE TITLE
Lock over updates

### ISSUE THREAD

**Issue by quoll** [threatgrid/asami#128]
Since transactions can now include entity updates, this leaves a window for modification between the entity queries and the graph transact step. Create a lock for this.

It's worth noting that transactions containing `tx-triples`, or a `tx-data` that has no maps will not require a lock over the `entities/build-triples` function, since it won't be querying.

**Comment by quoll** [comment]
We do not want a global lock here. Instead, it needs to be on the physical database, not on the connection object.

For in-memory databases, none of this matters, since the data is already immutable. If anyone else tried to modify the database they would get their own database with their own modifications back. The Database object ultimately returned for the connection will be a race between whoever modifies it (a race that we want to avoid), but it will be consistent either way.

Durable databases are more fragile. Modifications are atomic but the query/modify cycle needs to be protected. This will be based on the location of DB. This means that locks will be built from the canonical URL. To ensure this, we will want the JVM to:
- provide a lock per connection
- ensure that connections are returned on a canonical path, and not allow aliases to the same data (e.g. `asami:local://path` vs. `asami:local://another-path/../path`)

**Comment by jjtolton** [comment]
Interesting.  Are you thinking perhaps something along the lines of a locking context-manager?
```clojure
(d/with-lock db-url
  (let [e (d/q some-query (d/db conn))] 
    (d/transact conn {:tx-data [{:db/ident e :some/attr some-data}]})))
```
?

**Comment by quoll** [comment]
Fixed in #123 and #129.

**Comment by quoll** [comment]
> Interesting. Are you thinking perhaps something along the lines of a locking context-manager?
> 
> ```clojure
> (d/with-lock db-url
>   (let [e (d/q some-query (d/db conn))] 
>     (d/transact conn {:tx-data [{:db/ident e :some/attr' some-data}]})))
> ```
> 
> ?

I hadn't, but I should have. It's now in PR #129 
See https://github.com/threatgrid/asami/commit/4adec3aa54bc8e3781e5252d402f2eaff5d19d07

**Comment by jjtolton** [comment]
Question about the [locking implementation](https://github.com/threatgrid/asami/commit/4adec3aa54bc8e3781e5252d402f2eaff5d19d07#diff-96593bc91b5615cadcb44aacd43819962fcf58af5afb82436970694c783336a9R42) -- is this concurrency lock on the process only or a file-system lock?  

Scenario: 

GraalVM compiled code using Asami to transact datoms, launched perhaps via CLI.  If X of these were launched concurrently, would that result in DB corruption if they were doing compare-and-swap style operations?

**Comment by jjtolton** [comment]
Perfect!  Just want to understand the behavior.
