### ISSUE TITLE
Pull projection operations into Asami

### ISSUE THREAD

**Issue by quoll** [threatgrid/asami#191]
Projection is a common operation for both Naga and Asami, and as such has been kept in the Zuko library. Asami's scope is widening, and sharing this code with Naga will both be less necessary, and an impediment to effective development.

Pull the [`zuko.projection` namespace](https://github.com/threatgrid/zuko/blob/main/src/zuko/projection.cljc) into Asami. If there are operations or conditions that appear to exist only for Naga compatibility, then these should be stripped down to just what Asami needs.

In the first instance, it should be possible to copy the namespace in, rename it, and update `asami.query` to refer to the new namespace.

**Comment by noprompt** [comment]
Completed by #196
