### ISSUE TITLE
Data Writer/Reader

### ISSUE THREAD

**Issue by quoll** [threatgrid/asami#81]
Flat files will contain length/type information followed by raw bytes.

This needs a reader/writer.

### Byte 0:
| Pattern | Type | Description |
|--------|------|-------------|
| 0xxxxxxx | string | 7 bits of length info. Up to 128 |
| 10xxxxxx | URI | 6 bits of length info. Up to 64 |
| 110xxxxx | keyword | 5 bits of length info. Up to 32 |
| 111xyyyy | variable | Type determined in low 4 bits |

If the pattern begins with `111` then the length will be in the following bytes. The following bits are:

| Bits | Description |
|-----|-------------|
| 5-7  | all 1             |
| 4     | Indicates the number of length bytes |
| 3-0 | type info     |

### Bytes 1, 2, 3, 4
If bit4 of Byte0 is 0 then the next byte contains the length (up to 256). If 1, then the next 2 bytes (16 bits) indicate the length. 2 byte lengths can be up to 32kB.

If the 16 bit value is negative (bit15 = 1), then the length is actually 4 bytes, with a total of 31 bits indicating length. This gives a total possible length of 2GB.

## Types
Bit3-Bit0 indicate the type information:

| Pattern | Type |
|--------|-------|
| 0000 | string |
| 0001 |  uri |
| 0010 | long |
| 0011 | double |
| 0100 | BigInt |
| 0101 | BigFloat |
| 0110 | timestamp |
| 0111 | keyword |
| 1000 | urn |
| 1001 | blob |
| 1010 | xsd encoded |

There are 5 available codes remaining.

Each one of the above will have functions for encoding/decoding the data from the remaining bytes. The XSD type is expected to be extensible: encoding to a type URI a separator char, and a string format for the data. The default types are described in [XML Schema Part 2: Datatypes](https://www.w3.org/TR/xmlschema-2/). In particular, see the [type hierarchy diagram](https://www.w3.org/TR/xmlschema-2/#built-in-datatypes).

**Comment by quoll** [comment]
This is implemented on the JVM. Will duplicate this ticket for the ClojureScript version

**Comment by tami5** [comment]
:heart_eyes:
